import test from "node:test";
import assert from "node:assert/strict";
import { applyPreferences, clamp, createInitialState, currentCandidate, DEFAULT_PREFERENCES, hydrateState, normalizePreferences, PROPERTIES, rankCandidates, recordDecision, RENTERS, scoreProperty, scoreRenter, serializeState, WEIGHTS } from "../dist/marketplace.js";

test("ships six property candidates and five renter candidates", () => { assert.equal(PROPERTIES.length, 6); assert.equal(RENTERS.length, 5); });
test("uses the documented four feature groups", () => { assert.deepEqual(Object.keys(WEIGHTS), ["price", "location", "fit", "mutual"]); });
test("weights sum to one", () => { assert.equal(Object.values(WEIGHTS).reduce((a, b) => a + b, 0), 1); });
test("clamp bounds numeric values", () => { assert.equal(clamp(20, 0, 10), 10); assert.equal(clamp(-2, 0, 10), 0); });
test("clamp replaces non-numeric values", () => { assert.equal(clamp("nope", 5, 10), 5); });
test("normalizes renter defaults", () => { assert.deepEqual(normalizePreferences("renter"), DEFAULT_PREFERENCES.renter); });
test("normalizes landlord defaults", () => { assert.deepEqual(normalizePreferences("landlord"), DEFAULT_PREFERENCES.landlord); });
test("rejects an unknown role", () => { assert.throws(() => normalizePreferences("agent"), /Role must/); });
test("falls back from unknown home type", () => { assert.equal(normalizePreferences("renter", { homeType: "Castle" }).homeType, "Any"); });
test("falls back from unknown pet policy", () => { assert.equal(normalizePreferences("landlord", { petPolicy: "Sometimes" }).petPolicy, "Either"); });
test("scores a property within zero to one hundred", () => { const value = scoreProperty(PROPERTIES[0]); assert.ok(value.score >= 0 && value.score <= 100); });
test("property score exposes all factors", () => { assert.deepEqual(Object.keys(scoreProperty(PROPERTIES[0]).factors), Object.keys(WEIGHTS)); });
test("matching budget improves price factor", () => { const low = scoreProperty(PROPERTIES[2], { budget: 2000 }).factors.price; const high = scoreProperty(PROPERTIES[2], { budget: 3300 }).factors.price; assert.ok(high > low); });
test("pet policy penalizes homes that reject pets", () => { const pet = scoreProperty(PROPERTIES[2], { petFriendly: true }).factors.fit; const noPet = scoreProperty(PROPERTIES[2], { petFriendly: false }).factors.fit; assert.ok(noPet > pet); });
test("home type preference affects fit", () => { const match = scoreProperty(PROPERTIES[2], { homeType: "Loft" }).factors.fit; const mismatch = scoreProperty(PROPERTIES[2], { homeType: "House" }).factors.fit; assert.ok(match > mismatch); });
test("mutual interest is explicit in property scoring", () => { assert.equal(scoreProperty(PROPERTIES[0]).factors.mutual, 100); assert.equal(scoreProperty(PROPERTIES[1]).factors.mutual, 58); });
test("property score provides reasons", () => { assert.ok(scoreProperty(PROPERTIES[0]).reasons.length >= 1); });
test("property scoring rejects missing candidates", () => { assert.throws(() => scoreProperty(null), /required/); });
test("renter scoring exposes all factors", () => { assert.deepEqual(Object.keys(scoreRenter(RENTERS[0]).factors), Object.keys(WEIGHTS)); });
test("renter income below target lowers income fit", () => { assert.ok(scoreRenter(RENTERS[1], { minIncome: 150000 }).factors.price < scoreRenter(RENTERS[1], { minIncome: 70000 }).factors.price); });
test("minimum stay changes renter fit", () => { assert.ok(scoreRenter(RENTERS[1], { minStay: 24 }).factors.fit < scoreRenter(RENTERS[1], { minStay: 9 }).factors.fit); });
test("renter scoring rejects missing candidates", () => { assert.throws(() => scoreRenter(null), /required/); });
test("renter rankings are descending", () => { const scores = rankCandidates("renter", DEFAULT_PREFERENCES.renter).map((item) => item.score); assert.deepEqual(scores, [...scores].sort((a, b) => b - a)); });
test("landlord rankings are descending", () => { const scores = rankCandidates("landlord", DEFAULT_PREFERENCES.landlord).map((item) => item.score); assert.deepEqual(scores, [...scores].sort((a, b) => b - a)); });
test("rankings exclude reviewed candidates", () => { assert.equal(rankCandidates("renter", DEFAULT_PREFERENCES.renter, [PROPERTIES[0].id]).some((item) => item.id === PROPERTIES[0].id), false); });
test("rankings reject an unknown role", () => { assert.throws(() => rankCandidates("agent", {}), /Role must/); });
test("initial state starts in renter mode", () => { assert.equal(createInitialState().role, "renter"); });
test("hydrateState rejects unsupported versions safely", () => { assert.deepEqual(hydrateState({ schemaVersion: 99 }), createInitialState()); });
test("hydrateState filters invalid swipes", () => { const state = hydrateState({ schemaVersion: 1, swipes: [{ candidateId: "x", decision: "hack" }] }); assert.equal(state.swipes.length, 0); });
test("applyPreferences changes the active role", () => { assert.equal(applyPreferences(createInitialState(), "landlord", {}).role, "landlord"); });
test("currentCandidate returns the highest ranked visible candidate", () => { const state = createInitialState(); assert.equal(currentCandidate(state).id, rankCandidates("renter", state.preferences.renter)[0].id); });
test("save retains the current candidate", () => { const state = createInitialState(); const id = currentCandidate(state).id; const next = recordDecision(state, id, "save", { now: "2026-01-01" }).state; assert.equal(currentCandidate(next).id, id); assert.ok(next.saved.includes(id)); });
test("pass advances the feed", () => { const state = createInitialState(); const id = currentCandidate(state).id; const next = recordDecision(state, id, "pass", { now: "2026-01-01" }).state; assert.notEqual(currentCandidate(next).id, id); });
test("interest creates a match only when reciprocal", () => { const state = createInitialState(); const mutual = rankCandidates("renter", state.preferences.renter).find((item) => item.mutualInterest); const result = recordDecision(state, mutual.id, "like", { now: "2026-01-01" }); assert.equal(result.matched, true); assert.equal(result.state.matches.length, 1); });
test("nonreciprocal interest does not create a match", () => { const state = createInitialState(); const candidate = PROPERTIES.find((item) => !item.mutualInterest); const result = recordDecision(state, candidate.id, "like", { now: "2026-01-01" }); assert.equal(result.matched, false); assert.equal(result.state.matches.length, 0); });
test("duplicate reciprocal interest does not duplicate a match", () => { let state = createInitialState(); const candidate = PROPERTIES.find((item) => item.mutualInterest); state = recordDecision(state, candidate.id, "like", { now: "2026-01-01" }).state; state = recordDecision(state, candidate.id, "like", { now: "2026-01-02" }).state; assert.equal(state.matches.length, 1); });
test("recordDecision rejects invalid decisions", () => { assert.throws(() => recordDecision(createInitialState(), PROPERTIES[0].id, "block"), /Decision must/); });
test("recordDecision rejects candidates from the other role", () => { assert.throws(() => recordDecision(createInitialState(), RENTERS[0].id, "like"), /not available/); });
test("serializeState round trips", () => { const state = createInitialState(); assert.deepEqual(hydrateState(JSON.parse(serializeState(state))), state); });
